plugins { id 'com.android.library' }
android {
    namespace 'org.b5software.cibyp.core'
    compileSdk 36
    defaultConfig { minSdk 26 }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
    api 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
    api 'com.squareup.okhttp3:okhttp:4.12.0'
    api 'com.google.android.gms:play-services-wearable:20.0.1'
    api 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.10.2'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20250517'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.12.0'
}
